spring.application.name=Student-Library-Management


server.port=7777

# MySQL Datasource configuration for connecting to mysql database
spring.datasource.url=jdbc:mysql://localhost:3306/student_library_march2025
spring.datasource.username=root
spring.datasource.password=Vicky098@
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA and Hibernate configuration
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect